### PR TITLE
adds read.tbl_json option + tests

### PR DESCRIPTION
**Pull request by adgaudio**
Make it easier to load a json file into tidyjson directly from a file path.

- the path to the sample.json fixture is hardcoded to ../../data/sample.json
- the test for this is super simple, which is probably fine?
- do we want other options to read.tbl_json?

@jeremystan

### CODE REVIEW

**Comment by adgaudio** [comment]
@jeremystan 

Thanks for the tips!  Wanna take a look again and let me know what you think?

"pretty" json refers to whether or not the json is printed in a human readable format (ie with indents and spaces in correct places)
I think what you meant was does the json correspond with the "json lines" standard -->  http://jsonlines.org/

**Comment by jeremystan** [comment]
Neat! I had never heard of the JSON lines standard. I would add something about that to the README.

I would prefer not to try to infer the type based upon the extension, rather define the function as something like:

```
read_json <- function(path, format = c("json", "lines")) {

# force format to be one of the accepted arguments or throw an error
format <- match.args(format)

if (format == "json") {
  text <- ...
} else { # format must be 'lines'
  text <- ...
}

text %>% tbl_json

}
```

This makes the behavior more explicit and transparent, and allows us to expand to support other types in the future if needed without having to rely on the file name.

**Comment by adgaudio** [comment]
@jeremystan   I just implemented a version of what you suggested.  

read_json <- function(path, format = c("json", "lines", "infer"))


#'   If "json", process the data like one large JSON record.
#'   If "jsonl", process the data one JSON record per line (json lines format)
#'   If "infer", the format is the suffix of the given filepath.

**Comment by jeremystan** [comment]
+1, looks great

**Pull request merged**
